name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build dependencies
      run: python setup.py build_ext --inplace

    - name: Run assignment
      run: python index.py

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automatically update image"
